language: go
env: 
  - TRAVIS_NODE_VERSION="5"
install:
  # Hugo
  - go get -v github.com/spf13/hugo

  # Node
  - sudo rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - sudo npm install
  - sudo npm install -g gulp

  # S3 Sync
  - sudo pip install s3cmd
script:
  - npm run build publish 
deploy:
  # Staging environment
  - provider: script
    script: s3cmd sync ./public --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://preview.mrmatt57.org/
    on:
      branch: release-staging
  # Staging environment
  - provider: script
    script: s3cmd sync ./public --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://mrmatt57.org/
    on:
      branch: master
notifications:
    email:
        on_failure: always