language: node_js
node_js:
  - "5"
install:
  # Hugo - https://gohugo.io/overview/installing/
  - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

  # Node - https://nodejs.org/en/download/
  - npm install
  - npm install -g gulp http-server pa11y pa11y-ci

  # S3 Sync - http://s3tools.org/download
  - sudo pip install s3cmd

  # ImageMagick - https://www.imagemagick.org/script/binary-releases.php
  #- apt-get install imagemagick # Already Installed on Travis-CI

script:
  # Set Base Url based on branch
  - case "$TRAVIS_BRANCH" in ("master") BASE_URL="https://mrmatt.io/" ;; ("release-staging") BASE_URL="https://beta.mrmatt.io/" ;; (*) BASE_URL="http://localhost:8080" ;; esac

  # Build
  - gulp publish --baseUrl=$BASE_URL

  # Test
  - http-server ./public --silent &
  - pa11y-ci --sitemap http://localhost:8080/sitemap.xml --sitemap-find "$BASE_URL" --sitemap-replace "http://localhost:8080/"
cache:
  bundler: true
  pip: true
  directories:
  - node_modules
deploy:
  # Staging environment
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh beta.mrmatt.io 52361 $KEYCDN_APIKEY"
    on:
      branch: release-staging
  # Production environment
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh mrmatt.io 52360 $KEYCDN_APIKEY"
    on:
      branch: master
notifications:
    email: