language: go
install: go get -v github.com/spf13/hugo
before_script:
  - npm install -g gulp
script:
  - npm run build publish 
  - sudo pip install s3cmd
deploy:
  # Staging environment
  - provider: script
    script: s3cmd sync ./public --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://preview.mrmatt57.org/
    on:
      branch: release-staging
  # Staging environment
  - provider: script
    script: s3cmd sync ./public --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://mrmatt57.org/
    on:
      branch: master
notifications:
    email:
        on_failure: always